import { SiteHeader, SiteFooter } from "../../components/SiteHeader";
import { getCurrentUser } from "../../lib/auth";
import { getCreatorGames } from "../../lib/platform";
import GameActions from "./GameActions";
import { copy, getLocale, numberLocale } from "../../lib/i18n";
import { parseMultiplayerModes, parseSupportedLocales } from "../../lib/games";

export const dynamic = "force-dynamic";
export default async function DashboardPage() {
  const locale = await getLocale();
  const user = await getCurrentUser();
  if (!user) return <main><SiteHeader /><section className="login-gate dashboard-gate"><span>CREATOR DASHBOARD</span><h1>{copy(locale, "登入後查看你的作品。", "Sign in to view your games.")}</h1><a className="primary-button" href="/login?next=/dashboard">{copy(locale, "登入", "Sign in")} <span>↗</span></a></section><SiteFooter /></main>;
  const games = await getCreatorGames(user.id);
  const totalPlays = games.reduce((sum, game) => sum + Number(game.plays || 0), 0);
  return <main><SiteHeader /><section className="dashboard-head"><div><p className="eyebrow"><span /> CREATOR DASHBOARD</p><h1>{copy(locale, "作品控制台", "Creator dashboard")}</h1><p>{user.email}</p></div><div className="dashboard-actions"><a className="security-button" href="/account/security">{copy(locale, "帳號安全", "Account security")}</a><a className="primary-button" href="/upload">{copy(locale, "發布新遊戲", "Publish a game")} <span>↗</span></a><form action="/auth/signout" method="post"><button>{copy(locale, "登出", "Sign out")}</button></form></div></section><section className="dashboard-stats"><div><strong>{games.length}</strong><span>{copy(locale, "作品", "Games")}</span></div><div><strong>{games.filter((game) => game.status === "published").length}</strong><span>{copy(locale, "公開中", "Published")}</span></div><div><strong>{totalPlays.toLocaleString(numberLocale(locale))}</strong><span>{copy(locale, "累積遊玩", "Total plays")}</span></div></section><section className="dashboard-list"><div className="list-heading"><h2>{copy(locale, "你的作品", "Your games")}</h2><span>{copy(locale, "最新更新", "Last updated")}</span></div>{games.length ? games.map((game) => <article key={String(game.id)} className="dashboard-row"><a className="mini-cover" href={`/games/${String(game.slug)}`}>O</a><div><a href={`/games/${String(game.slug)}`}><strong>{String(locale === "en" ? game.title_en || game.title_zh : game.title_zh)}</strong></a><span>{copy(locale, `版本 ${String(game.version || "1.0.0")} · ${Number(game.plays || 0).toLocaleString("zh-TW")} 次遊玩`, `Version ${String(game.version || "1.0.0")} · ${Number(game.plays || 0).toLocaleString("en-US")} plays`)}</span></div><span className={`status-pill ${String(game.status)}`}>{locale === "en" ? (String(game.status) === "published" ? "Published" : "Hidden") : String(game.release_status || game.status)}</span><time>{String(game.updated_at).slice(0, 10)}</time><GameActions locale={locale} gameId={String(game.id)} initialStatus={String(game.status)} initialAllowDownload={Boolean(game.allow_download)} initialCloudSavesEnabled={Boolean(game.cloud_saves_enabled)} initialMultiplayerEnabled={Boolean(game.multiplayer_enabled)} initialMultiplayerMaxPlayers={Number(game.multiplayer_max_players || 4)} initialMultiplayerModes={parseMultiplayerModes(game.multiplayer_modes)} initialSupportedLocales={parseSupportedLocales(game.supported_locales)} initialDefaultLocale={String(game.default_locale || "zh-Hant")} /></article>) : <div className="empty-state"><strong>{copy(locale, "還沒有作品。", "No games yet.")}</strong><span>{copy(locale, "發布第一款網頁遊戲建置，幾分鐘內就能分享。", "Publish your first browser-ready game build and share it within minutes.")}</span><a href="/upload">{copy(locale, "開始上傳", "Start uploading")} ↗</a></div>}</section>{user.role === "admin" && <a className="admin-shortcut" href="/admin">{copy(locale, "前往管理與檢舉中心", "Open moderation center")} →</a>}<SiteFooter /></main>;
}
